extra_settings:
  # For how long outside the scheduled (start, stop) interval can the student
  # login still be considered valid
  student_login_time_spread: 5:00 # Time given in the 'minutes:seconds' format


semester:
  start_date: 2016-09-26
  end_date: 2017-01-22

  schedule_overrides:
    - holiday_date: 2016-11-11 # WW1 Armistice Day
      completed_on: 2017-01-23
    - holiday_date: 2017-01-07 # Orthodox Christmas
      completed_on: 2017-01-24


courses:
  PJISP_E3:
    teacher: hubert.farnsworth@mars.edu
    weekly_lab_schedule:
      Monday:
        - " 9:30 - 12:45"
      Tuesday:
        - "10:00 - 13:15"
        - "18:30 - 21:45"
      Wednesday:
        - " 7:00 - 10:15"
        - "18:00 - 21:15"
      Friday:
        - "12:30 - 15:45"

  PP_E3:
    teacher: amy.wong@mars.edu
    weekly_lab_schedule:
      Monday:
        - "14:30 - 16:00"
        - "16:30 - 18:00"
        - "20:30 - 22:00"

  OP_E3:
    teacher: ogden.wernstrom@mars.edu
    weekly_lab_schedule:
      Tuesday:
        - "13:30 - 16:45"
      Thursday:
        - "10:45 - 14:00"
